/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.osumnjiceni;

import forme.osumnjiceni.model.ModelTabeleOsumnjiceni;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.Osumnjiceni;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Operacija;

/**
 *
 * @author  Aleksandar Randjelovic
 */
public class FormaPretragaOsumnjicenih extends javax.swing.JFrame {

    private List<Osumnjiceni> listaOsumnjicenih;
    private String[] poljaZaPretragu = {"Ime i prezime", "JMBG", "Mesto", "Zanimanje"};

    public FormaPretragaOsumnjicenih() {
        initComponents();
        setLocationRelativeTo(null);
        postaviKomponente();
        postaviTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcmbKriterijumPretrage = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jtxtVredenostPretrage = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabelaOsumnjiceni = new javax.swing.JTable();
        jbtnPretragaOsumnjicenih = new javax.swing.JButton();
        jbtnPrikaziPodatke = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga osumnjicenih");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalji pretrage osumnjicenih", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Kriterijum pretrage:");

        jcmbKriterijumPretrage.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jcmbKriterijumPretrage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbKriterijumPretrageActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Vrednost pretrage:");

        jtxtVredenostPretrage.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtVredenostPretrage)
                    .addComponent(jcmbKriterijumPretrage, 0, 201, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcmbKriterijumPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtVredenostPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtabelaOsumnjiceni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabelaOsumnjiceni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelaOsumnjiceniMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabelaOsumnjiceni);

        jbtnPretragaOsumnjicenih.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jbtnPretragaOsumnjicenih.setText("Pretraga osumnjicenih");
        jbtnPretragaOsumnjicenih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPretragaOsumnjicenihActionPerformed(evt);
            }
        });

        jbtnPrikaziPodatke.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jbtnPrikaziPodatke.setText("Detaljni podaci o osumnjicenom");
        jbtnPrikaziPodatke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrikaziPodatkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnPrikaziPodatke, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnPretragaOsumnjicenih, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnPrikaziPodatke, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPretragaOsumnjicenih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPrikaziPodatkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrikaziPodatkeActionPerformed
        int selectedRow = jtabelaOsumnjiceni.getSelectedRow();
        ModelTabeleOsumnjiceni model = (ModelTabeleOsumnjiceni) jtabelaOsumnjiceni.getModel();
        Osumnjiceni osumnjiceni = model.vratiOsumnjicenog(selectedRow);
        FormaUnosOsumnjicenog fuo = new FormaUnosOsumnjicenog(false,true,true,this);
        fuo.postaviPodatkeOOsumnjicenom(osumnjiceni);
//        fuo.postaviIzgledForme(OperacijaForme.UPRAVLJANJE);
        fuo.setVisible(true);
        JOptionPane.showMessageDialog(null, "Podaci o osumnjičenom uspešno prikazani");
    }//GEN-LAST:event_jbtnPrikaziPodatkeActionPerformed

    private void jtabelaOsumnjiceniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelaOsumnjiceniMouseClicked
        jbtnPrikaziPodatke.setEnabled(true);
    }//GEN-LAST:event_jtabelaOsumnjiceniMouseClicked

    private void jbtnPretragaOsumnjicenihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPretragaOsumnjicenihActionPerformed
        String vrednostPretrage = jtxtVredenostPretrage.getText().toLowerCase().trim();
        String poljeZaPretragu = (String) jcmbKriterijumPretrage.getSelectedItem();

        List<Osumnjiceni> filtriranaListaOsumnjicenih = new LinkedList<>();
        if (vrednostPretrage.equals("")) {
            filtriranaListaOsumnjicenih = listaOsumnjicenih;
            JOptionPane.showMessageDialog(this, "Unesite vrednost pretrage.");
        } else {
            switch (poljeZaPretragu) {
                case "Ime i prezime":
                    for (Osumnjiceni osumnjiceni : listaOsumnjicenih) {
                        if (osumnjiceni.getImePrezime().toLowerCase().contains(vrednostPretrage)) {
                            filtriranaListaOsumnjicenih.add(osumnjiceni);
                        }
                    }
                    break;
                case "JMBG":
                    for (Osumnjiceni osumnjiceni : listaOsumnjicenih) {
                        if (osumnjiceni.getJMBG().startsWith(vrednostPretrage)) {
                            filtriranaListaOsumnjicenih.add(osumnjiceni);
                        }
                    }
                    break;
                case "Mesto":
                    for (Osumnjiceni osumnjiceni : listaOsumnjicenih) {
                        if (osumnjiceni.getMesto().toString().toLowerCase().contains(vrednostPretrage)) {
                            filtriranaListaOsumnjicenih.add(osumnjiceni);
                        }
                    }
                    break;
                case "Zanimanje":
                    for (Osumnjiceni osumnjiceni : listaOsumnjicenih) {
                        if (osumnjiceni.getZanimanje().toLowerCase().contains(vrednostPretrage)) {
                            filtriranaListaOsumnjicenih.add(osumnjiceni);
                        }
                    }
                    break;
                default:
                    filtriranaListaOsumnjicenih = listaOsumnjicenih;
            }
        }
        if(filtriranaListaOsumnjicenih.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sistem ne moze da nadje osumnjicenog po zadatoj vrednosti");
            return;
        } else {
            JOptionPane.showMessageDialog(null, "Osumnjičeni su uspešno prikazani");
        }
        ModelTabeleOsumnjiceni model = new ModelTabeleOsumnjiceni(filtriranaListaOsumnjicenih);
        jtabelaOsumnjiceni.setModel(model);
    }//GEN-LAST:event_jbtnPretragaOsumnjicenihActionPerformed

    private void jcmbKriterijumPretrageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbKriterijumPretrageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbKriterijumPretrageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnPretragaOsumnjicenih;
    private javax.swing.JButton jbtnPrikaziPodatke;
    private javax.swing.JComboBox jcmbKriterijumPretrage;
    private javax.swing.JTable jtabelaOsumnjiceni;
    private javax.swing.JTextField jtxtVredenostPretrage;
    // End of variables declaration//GEN-END:variables

    private void postaviKomponente() {
        jbtnPrikaziPodatke.setEnabled(false);

        jcmbKriterijumPretrage.removeAllItems();
        jcmbKriterijumPretrage.setModel(new DefaultComboBoxModel(poljaZaPretragu));
    }

    private void postaviTabelu() {
        try {
            TransferObjekatZahtev zahtev = new TransferObjekatZahtev();
            zahtev.setOperacija(Operacija.VRATI_OSUMNJICENE);
            Komunikacija.getInstance().posaljiZahtev(zahtev);
            TransferObjekatOdgovor odgovor = Komunikacija.getInstance().primiOdgovor();
            if (odgovor.getIzuzetak() != null) {
                JOptionPane.showMessageDialog(this, (String) odgovor.getIzuzetak());
                return;
            }
            listaOsumnjicenih = (List<Osumnjiceni>) odgovor.getRezultat();
            ModelTabeleOsumnjiceni modelTabele = new ModelTabeleOsumnjiceni(listaOsumnjicenih);
            jtabelaOsumnjiceni.setModel(modelTabele);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Server je ugasen. Gasenje klijenta!");
            System.exit(0);
        }
    }

    void obrisiRed(Osumnjiceni osumnjiceni) {
        jbtnPrikaziPodatke.setEnabled(false);
        ModelTabeleOsumnjiceni model = (ModelTabeleOsumnjiceni) jtabelaOsumnjiceni.getModel();
        model.obrisiRed(osumnjiceni);
    }

    void izmeniRed(Osumnjiceni osumnjiceni) {
        jbtnPrikaziPodatke.setEnabled(false);
        ModelTabeleOsumnjiceni model = (ModelTabeleOsumnjiceni) jtabelaOsumnjiceni.getModel();
        model.izmeniRed(osumnjiceni);
    }
}
