/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.osumnjiceni;

import forme.GlavnaFormaKlijent;
import java.util.Date;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import komunikacija.Komunikacija;
import model.Mesto;
import model.Osumnjiceni;
import model.Predmet;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Operacija;
import util.OperacijaForme;
import validacija.Validacija;

/**
 *
 * @author Aleksandar Randjelovic
 */
public class FormaUnosOsumnjicenog extends javax.swing.JFrame {

    private Osumnjiceni osumnjiceni;
    private FormaPretragaOsumnjicenih formaPretragaOsumnjicenih;
    private GlavnaFormaKlijent glavnaFormaKlijent;
    private List<Predmet> listaPredmeta;
    boolean osudjivanost = false;
    ButtonGroup bg;
    
    /**
     * Creates new form FormaUnosClana
     */
    public FormaUnosOsumnjicenog(boolean btnUnesi, boolean btnObrisi, boolean btnIzmeni) {
        initComponents();
        
        jbtnUnesi.setEnabled(btnUnesi);
        jbtnObrisi.setEnabled(btnObrisi);
        jbtnIzmeni.setEnabled(btnIzmeni);
        
        postaviKomponente();

        
    }

    public FormaUnosOsumnjicenog(FormaPretragaOsumnjicenih formaPretragaOsumnjicenih) {
        initComponents();
        postaviKomponente();
        this.formaPretragaOsumnjicenih = formaPretragaOsumnjicenih;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtMaticniBroj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtAdresa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtZanimanje = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jcmbMesto = new javax.swing.JComboBox();
        jlblIme = new javax.swing.JLabel();
        jlblMaticni = new javax.swing.JLabel();
        jlblAdresa = new javax.swing.JLabel();
        jlblZanimanje = new javax.swing.JLabel();
        jdcDatumRodjenja = new com.toedter.calendar.JDateChooser();
        jrbDa = new javax.swing.JRadioButton();
        jrbNe = new javax.swing.JRadioButton();
        jlblPrezime = new javax.swing.JLabel();
        jlbDatum = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtnUnesi = new javax.swing.JButton();
        jbtnObrisi = new javax.swing.JButton();
        jbtnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos clana");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalji o clanu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Ime:");

        jtxtIme.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Prezime:");

        jtxtPrezime.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Datum rodjenja:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Maticni broj:");

        jtxtMaticniBroj.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("Adresa:");

        jtxtAdresa.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jtxtAdresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAdresaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Zanimanje:");

        jtxtZanimanje.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("Osudjivanost:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setText("Mesto:");

        jcmbMesto.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jlblIme.setText(".");

        jlblMaticni.setText(".");

        jlblAdresa.setText(".");

        jlblZanimanje.setText(".");

        jdcDatumRodjenja.setDateFormatString("yyyy-MM-dd");
        jdcDatumRodjenja.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jrbDa.setText("Da");
        jrbDa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDaActionPerformed(evt);
            }
        });

        jrbNe.setText("Ne");
        jrbNe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNeActionPerformed(evt);
            }
        });

        jlblPrezime.setText(".");

        jlbDatum.setText(".");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblMaticni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbDatum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblPrezime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtMaticniBroj, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdcDatumRodjenja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblIme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtIme)
                            .addComponent(jtxtPrezime)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jlblZanimanje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcmbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jrbDa)
                                .addGap(36, 36, 36)
                                .addComponent(jrbNe)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtZanimanje))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblAdresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtAdresa))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblIme)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblPrezime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbDatum)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMaticniBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblMaticni)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblAdresa)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtZanimanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jlblZanimanje)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jrbDa)
                            .addComponent(jrbNe))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jcmbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jbtnUnesi.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jbtnUnesi.setText("Unesi clana");
        jbtnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUnesiActionPerformed(evt);
            }
        });

        jbtnObrisi.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jbtnObrisi.setText("Obrisi clana");
        jbtnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiActionPerformed(evt);
            }
        });

        jbtnIzmeni.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jbtnIzmeni.setText("Sacuvaj izmene");
        jbtnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnUnesi, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jbtnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnUnesi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUnesiActionPerformed
        String imePrezime = jtxtIme.getText() + " " + jtxtPrezime.getText();
        Date datumRodjenja = jdcDatumRodjenja.getDate();
//        System.out.println(((JTextField) jdcDatumUclanjenja.getDateEditor().getUiComponent()).getText());
//        System.out.println(new SimpleDateFormat("yyyy-MM-dd").format(jdcDatumUclanjenja.getDate()));
        String JMBG = jtxtMaticniBroj.getText();
        String adresa = jtxtAdresa.getText();
        String zanimanje = jtxtZanimanje.getText();
        Mesto m = (Mesto) jcmbMesto.getSelectedItem();

        TransferObjekatZahtev zahtev = new TransferObjekatZahtev();
        try {
            if (validateFields()) {
                Osumnjiceni osumnjiceni = new Osumnjiceni(imePrezime, JMBG, datumRodjenja, adresa, zanimanje, osudjivanost, m);
                zahtev.setOperacija(Operacija.UNOS_OSUMNJICENOG);
                zahtev.setParametar(osumnjiceni);
                Komunikacija.getInstance().posaljiZahtev(zahtev);
                TransferObjekatOdgovor odgovor = Komunikacija.getInstance().primiOdgovor();
                if (odgovor.getIzuzetak() == null) {
                    JOptionPane.showMessageDialog(this, "Sistem je zapamtio osumnjicenog!");
                    this.dispose();
                } else {
                    throw (Exception) odgovor.getIzuzetak();
                }
            }
        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, "Sistem ne moze da unese clana!");
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jbtnUnesiActionPerformed

    private void jbtnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiActionPerformed
        try {
            TransferObjekatZahtev zahtev = new TransferObjekatZahtev();
            zahtev.setOperacija(Operacija.BRISANJE_OSUMNJICENOG);
            zahtev.setParametar(osumnjiceni);
            Komunikacija.getInstance().posaljiZahtev(zahtev);
            TransferObjekatOdgovor odgovor = Komunikacija.getInstance().primiOdgovor();
            if (odgovor.getIzuzetak() == null) {
                JOptionPane.showMessageDialog(this, odgovor.getPoruka());
                formaPretragaOsumnjicenih.obrisiRed(osumnjiceni);
                this.dispose();
            } else {
                throw (Exception) odgovor.getIzuzetak();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jbtnObrisiActionPerformed

    private void jbtnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniActionPerformed
        jrbDa.setActionCommand("osudjivan");
        jrbNe.setActionCommand("nije osudjivan");
        
        if(bg.getSelection().getActionCommand() == "osudjivan") {
            osudjivanost = true;
        } else if (bg.getSelection().getActionCommand() == "nije osudjivan") {
            osudjivanost = false;
        }
        
        System.out.println(osudjivanost);
        
        try {
            TransferObjekatZahtev zahtev = new TransferObjekatZahtev();
            if (validateFields()) {
                zahtev.setOperacija(Operacija.IZMENA_OSUMNJICENOG);
                Osumnjiceni osumnjiceniIzmena = new Osumnjiceni(this.osumnjiceni.getOsumnjiceniID(), jtxtIme.getText() + " " + jtxtPrezime.getText(), jtxtMaticniBroj.getText(), jdcDatumRodjenja.getDate(), jtxtAdresa.getText(), jtxtZanimanje.getText(), osudjivanost , (Mesto) jcmbMesto.getSelectedItem());
                zahtev.setParametar(osumnjiceniIzmena);
                Komunikacija.getInstance().posaljiZahtev(zahtev);
                TransferObjekatOdgovor odgovor = Komunikacija.getInstance().primiOdgovor();
                if (odgovor.getIzuzetak() == null) {
                    JOptionPane.showMessageDialog(this, odgovor.getPoruka());
                    formaPretragaOsumnjicenih.izmeniRed(osumnjiceniIzmena);
                    this.dispose();
                } else {
                    throw (Exception) odgovor.getIzuzetak();
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jbtnIzmeniActionPerformed

    private void jrbNeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNeActionPerformed
        osudjivanost = false;
        jrbNe.setSelected(osudjivanost);
    }//GEN-LAST:event_jrbNeActionPerformed

    private void jrbDaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDaActionPerformed
        osudjivanost = true;
        jrbDa.setSelected(osudjivanost);
    }//GEN-LAST:event_jrbDaActionPerformed

    private void jtxtAdresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAdresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAdresaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnIzmeni;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JButton jbtnUnesi;
    private javax.swing.JComboBox jcmbMesto;
    private com.toedter.calendar.JDateChooser jdcDatumRodjenja;
    private javax.swing.JLabel jlbDatum;
    private javax.swing.JLabel jlblAdresa;
    private javax.swing.JLabel jlblIme;
    private javax.swing.JLabel jlblMaticni;
    private javax.swing.JLabel jlblPrezime;
    private javax.swing.JLabel jlblZanimanje;
    private javax.swing.JRadioButton jrbDa;
    private javax.swing.JRadioButton jrbNe;
    private javax.swing.JTextField jtxtAdresa;
    private javax.swing.JTextField jtxtIme;
    private javax.swing.JTextField jtxtMaticniBroj;
    private javax.swing.JTextField jtxtPrezime;
    private javax.swing.JTextField jtxtZanimanje;
    // End of variables declaration//GEN-END:variables

    private void postaviKomponente() {
        setLocationRelativeTo(null);
        this.setTitle("Unos clana");
        groupButton();
        this.repaint();
        this.pack();
        ucitajComboBox();
        podesiLabele(false);
        jrbNe.setSelected(true);
    }

    void postaviIzgledForme(int operacijaForme) {
        if (operacijaForme == OperacijaForme.UPRAVLJANJE) {
            this.setTitle("Izmena/brisanje clana");
            jbtnUnesi.setVisible(false);
            jbtnIzmeni.setVisible(true);
            jbtnObrisi.setVisible(true);
            this.repaint();
            this.pack();
        }
    }

    void postaviPodatkeOOsumnjicenom(Osumnjiceni osumnjiceni) {
        this.osumnjiceni = osumnjiceni;
        String[] imePrezime = osumnjiceni.getImePrezime().split(" ");
        jtxtIme.setText(imePrezime[0]);
        jtxtPrezime.setText(imePrezime[1]);
        jtxtAdresa.setText(osumnjiceni.getAdresa());
        jtxtMaticniBroj.setText(osumnjiceni.getJMBG());
        jdcDatumRodjenja.setDate(osumnjiceni.getDatumRodjenja());
        jtxtZanimanje.setText(osumnjiceni.getZanimanje());
        jcmbMesto.getModel().setSelectedItem(osumnjiceni.getMesto());
        
        if(osumnjiceni.isOsudjivanost()) {
            jrbDa.setSelected(true);
        } else {
            jrbNe.setSelected(true);
        }
    }

    public boolean validateFields() {

        //ime, prezime, datumUclanjenja, brojRacuna, maticniBroj, ulica, broj, kontaktTelefon
        podesiLabele(true);
        podesiVrednostLabela("");

        if (!Validacija.validateField(jtxtIme, jlblIme, "Unesite polje za ime")) {
            return false;
        } else if (!Validacija.validateField(jtxtPrezime, jlblPrezime, "Unesite polje za prezime")) {
            return false;
        } else if (!Validacija.validateField((JTextField) jdcDatumRodjenja.getDateEditor().getUiComponent(), jlbDatum, "Izaberite polje za datum")) {
            return false;
        } else if (!Validacija.validateField(jtxtMaticniBroj, jlblMaticni, "Unesite polje za maticni broj")) {
            return false;
        } else if (!Validacija.validateField(jtxtAdresa, jlblAdresa, "Unesite polje za adresu")) {
            return false;
        } else if (!Validacija.validateField(jtxtZanimanje, jlblZanimanje, "Unesite polje za broj")) {
            return false;
        } else {
            return true;
        }
    }

    public void ucitajComboBox() {
        try {
            jcmbMesto.removeAllItems();

            TransferObjekatZahtev zahtev = new TransferObjekatZahtev();
            zahtev.setOperacija(Operacija.VRATI_MESTA);
            Komunikacija.getInstance().posaljiZahtev(zahtev);
            TransferObjekatOdgovor odgovor = Komunikacija.getInstance().primiOdgovor();
            if (odgovor.getIzuzetak() != null) {
                throw (Exception) odgovor.getIzuzetak();
            }
            List<Mesto> listaMesta = (List<Mesto>) odgovor.getRezultat();

            for (Mesto mesto : listaMesta) {
                jcmbMesto.addItem(mesto);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Server je ugasen. Gasenje klijenta!");
            System.exit(0);
        }
    }

    private void podesiLabele(boolean bool) {
        jlblIme.setVisible(bool);
        jlblIme.revalidate();

        jlblPrezime.setVisible(bool);
        jlblPrezime.revalidate();

        jlbDatum.setVisible(bool);
        jlbDatum.revalidate();

        jlblAdresa.setVisible(bool);
        jlblAdresa.revalidate();

        jlblMaticni.setVisible(bool);
        jlblMaticni.revalidate();

        jlblZanimanje.setVisible(bool);
        jlblZanimanje.revalidate();

        this.pack();
        this.repaint();
    }

    private void podesiVrednostLabela(String string) {
        jlblIme.setText(string);
        jlblPrezime.setText(string);
        jlbDatum.setText(string);
        jlblAdresa.setText(string);
        jlblMaticni.setText(string);
        jlblZanimanje.setText(string);

        this.pack();
        this.repaint();
    }

    private void groupButton() {
        bg = new ButtonGroup();
        bg.add(jrbDa);
        bg.add(jrbNe);
    }
   
} 
