/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.tuzioci;

import forme.osumnjiceni.*;
import forme.osumnjiceni.model.ModelTabeleOsumnjiceni;
import forme.tuzioci.model.ModelTabeleTuzioci;
import java.util.LinkedList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.Osumnjiceni;
import model.Tuzilac;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Operacija;

/**
 *
 * @author  Aleksandar Randjelovic
 */
public class FormaPretragaTuzilaca extends javax.swing.JFrame {

    private List<Tuzilac> listaTuzilaca;
    private String[] poljaZaPretragu = {"Ime i prezime", "Radni staz veci od", "Broj predmeta veci od", "Dostupnost"};

    /**
     * Creates new form FormaPretragaClanova
     */
    public FormaPretragaTuzilaca() {
        initComponents();
        setLocationRelativeTo(null);
        postaviKomponente();
        postaviTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcmbKriterijumPretrage = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jtxtVredenostPretrage = new javax.swing.JTextField();
        jbtnPretragaOsumnjicenih = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabelaTuzioci = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pretraga clana");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalji pretrage tuzilaca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setText("Kriterijum pretrage:");

        jcmbKriterijumPretrage.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jcmbKriterijumPretrage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbKriterijumPretrageActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setText("Vrednost pretrage:");

        jtxtVredenostPretrage.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N

        jbtnPretragaOsumnjicenih.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jbtnPretragaOsumnjicenih.setText("Pretraga tuzilaca");
        jbtnPretragaOsumnjicenih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPretragaOsumnjicenihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtVredenostPretrage)
                    .addComponent(jcmbKriterijumPretrage, 0, 201, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnPretragaOsumnjicenih, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jcmbKriterijumPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtVredenostPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jbtnPretragaOsumnjicenih, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtabelaTuzioci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabelaTuzioci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelaTuziociMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabelaTuzioci);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Detalji pretrage tuzilaca");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtabelaTuziociMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelaTuziociMouseClicked
    }//GEN-LAST:event_jtabelaTuziociMouseClicked

    private void jbtnPretragaOsumnjicenihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPretragaOsumnjicenihActionPerformed
        String vrednostPretrage = jtxtVredenostPretrage.getText().toLowerCase().trim();
        String poljeZaPretragu = (String) jcmbKriterijumPretrage.getSelectedItem();

        List<Tuzilac> filtriranaListaTuzilaca = new LinkedList<>();
        if (vrednostPretrage.equals("")) {
            filtriranaListaTuzilaca = listaTuzilaca;
            JOptionPane.showMessageDialog(this, "Unesite vrednost pretrage.");
        } else {
            switch (poljeZaPretragu) {
                case "Ime i prezime":
                    for (Tuzilac tuzilac : listaTuzilaca) {
                        if (tuzilac.getImePrezime().toLowerCase().contains(vrednostPretrage)) {
                            filtriranaListaTuzilaca.add(tuzilac);
                        }
                    }
                    break;
                case "Radni staz veci od":
                    for (Tuzilac tuzilac : listaTuzilaca) {
                        if (tuzilac.getRadniStaz() > Integer.parseInt(vrednostPretrage)) {
                            filtriranaListaTuzilaca.add(tuzilac);
                        }
                    }
                    break;
                case "Broj predmeta veci od":
                    for (Tuzilac tuzilac : listaTuzilaca) {
                        if (tuzilac.getBrojPredmeta() > Integer.parseInt(vrednostPretrage)) {
                            filtriranaListaTuzilaca.add(tuzilac);
                        }
                    }
                    break;
                case "Dostupnost":
                    boolean vrednost = false;
                        if(vrednostPretrage.trim().toLowerCase().equals("dostupan")) {
                            vrednost = true;
                        } else if(vrednostPretrage.trim().toLowerCase().equals("nije dostupan")) {
                            vrednost = false;
                        }
                    for (Tuzilac tuzilac : listaTuzilaca) {
                        
                        if (tuzilac.isDostupan() == vrednost) {
                            filtriranaListaTuzilaca.add(tuzilac);
                        }
                    }
                    break;
                default:
                    filtriranaListaTuzilaca = listaTuzilaca;
            }
        }
        if(filtriranaListaTuzilaca.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sistem ne moze da nadje tuzioca po zadatoj vrednosti");
            return;
        }
        ModelTabeleTuzioci model = new ModelTabeleTuzioci(filtriranaListaTuzilaca);
        jtabelaTuzioci.setModel(model);
    }//GEN-LAST:event_jbtnPretragaOsumnjicenihActionPerformed

    private void jcmbKriterijumPretrageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbKriterijumPretrageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbKriterijumPretrageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnPretragaOsumnjicenih;
    private javax.swing.JComboBox jcmbKriterijumPretrage;
    private javax.swing.JTable jtabelaTuzioci;
    private javax.swing.JTextField jtxtVredenostPretrage;
    // End of variables declaration//GEN-END:variables

    private void postaviKomponente() {

        jcmbKriterijumPretrage.removeAllItems();
        jcmbKriterijumPretrage.setModel(new DefaultComboBoxModel(poljaZaPretragu));
    }

    private void postaviTabelu() {
        try {
            TransferObjekatZahtev zahtev = new TransferObjekatZahtev();
            zahtev.setOperacija(Operacija.VRATI_TUZIOCE);
            Komunikacija.getInstance().posaljiZahtev(zahtev);
            TransferObjekatOdgovor odgovor = Komunikacija.getInstance().primiOdgovor();
            if (odgovor.getIzuzetak() != null) {
                JOptionPane.showMessageDialog(this, (String) odgovor.getIzuzetak());
                return;
            }
            listaTuzilaca = (List<Tuzilac>) odgovor.getRezultat();
            ModelTabeleTuzioci modelTabele = new ModelTabeleTuzioci(listaTuzilaca);
            jtabelaTuzioci.setModel(modelTabele);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Server je ugasen. Gasenje klijenta!");
            System.exit(0);
        }
    }
}
